# Este arquivo configura o projeto no Read the Docs.
# Mais informações: https://docs.readthedocs.io/en/latest/config.html

# Configurações gerais para o projeto.
version: 2

# Especifica o formato da documentação. `sphinx` é o formato usado para documentação com Sphinx.
sphinx:
  configuration: docs/conf.py

# Configura o ambiente de Python e os pacotes a serem instalados.
python:
  version: "3.11"
  install:
    - requirements: docs/requirements.txt

# Configura o comando de construção da documentação.
build:
  os: ubuntu-22.04
  commands:
    - sphinx-build -b html docs docs/_build/html

# Adiciona arquivos que precisam ser incluídos na construção.
files:
  include:
    - docs/_static/
    - docs/_templates/
